### ISSUE TITLE
Avatar manager shows incorrect icons for avatars

### ISSUE THREAD

**Issue by Exotic-Retard** [FAForever/faf-moderator-client#1]
the icon previews dont correlate to the avatars. the rest of the info appears correct. some previews are empty.
the previews change upon client restart, and searching, so the process isnt deterministic it seems.

i dont know if this is some bug or just an incomplete feature.

**Comment by Brutus5000** [comment]
The previews in User Management tab or the previews in Avatars?
If in Avatars tab: Please add a screenshot of a wrong preview with ID, Preview and URL.

**Comment by Exotic-Retard** [comment]
its the avatar management tab - the preview isnt correct for the avatar name and other info, which does appear to be correct - for example the pizza avatar is showing a not-pizza.

whats more is that the preview changes on reload so it seems strange.
https://puu.sh/ymQxn/edb8594566.png

**Comment by Brutus5000** [comment]
Okay, this only happens if you sort by any column. Looks like the image has no "value" and is somehow not sorted along.
