### ISSUE TITLE
hidden map issues

### ISSUE THREAD

**Issue by PhilipJFryFAF** [FAForever/faf-moderator-client#101]
maps are not marked as hidden seemingly at random
eg.
![image](https://user-images.githubusercontent.com/24656673/65167482-f3883f00-da42-11e9-9605-6e0126f503cf.png)
![image](https://user-images.githubusercontent.com/24656673/65167490-f7b45c80-da42-11e9-9551-6c5bf877cfa6.png)
would be nice if hidden maps would have the respective box ticked

**Comment by Brutus5000** [comment]
Explanation: PhilipJFryFAF queried both after changing all maps to hidden.
In that case the original call shows not a different state, as it is cached by the API, while the search by the other key is not necessarily cached.
