### ISSUE TITLE
download links for maps/mods

### ISSUE THREAD

**Issue by PhilipJFryFAF** [FAForever/faf-moderator-client#102]
i'd like to have a "copy download link" feature for the maps and for the mods section of the moderation client

eg when right clicking on a specific version of a map or having the button next to the hide/unrate button

reason why i would really like to have this:
being able to easily download maps or mods that are marked as hidden

**Comment by Brutus5000** [comment]
Reminder for myself:
The solution lies within the `ViewHelper` class in the methods `buildMapVersionTableView` / `buildModVersionTableView`

**Comment by Brutus5000** [comment]
Fixed in #103
