### ISSUE TITLE
Show number of games, latest games and ratings

### ISSUE THREAD

**Issue by Brutus5000** [FAForever/faf-moderator-client#11]
requested by exotic-retard 

- [x] Add a new tab games
- [x] List number of total games at top then tableView with games and ratings
- [x] Add a switch for ladder only

**Comment by axel1200** [comment]
@Brutus5000 

> List  number of total games at top then tableView with games and ratings. 
Can we pls specify, what exactly that means. Do you want to display all games played last week e.g. ? And wahats a  "tableView with games and ratings"?
I am a little unsure what is acctually requested.
