### ISSUE TITLE
Add new map pool and matchmaker queue tables

### ISSUE THREAD

**Issue by Askaholic** [FAForever/faf-moderator-client#111]
Should add a way of writing data into the map pool and matchmaker queue tables:
https://github.com/FAForever/server/issues/567

This means being able to:
- Create/edit matchmaker queues
- Create/edit map pools
- ~Add map versions to a map pool~
- Add map pools to a matchmaker queue

**Comment by BlackYps** [comment]
This seems to be done?

**Comment by Brutus5000** [comment]
I'm extracting "Add map versions to a map pool" into a dedicated issue

**Comment by Brutus5000** [comment]
Matchmaker queues are managed here 
https://github.com/FAForever/db/blob/develop/migrations/R__070_matchmaker_queue.sql

The same thing could or maybe should be done for matchmaker queue map pools.
I do not plan on adding a UI for it. There hasn't been a single change ever (=in the last 12 months).
