### ISSUE TITLE
Add domain blacklist

### ISSUE THREAD

**Issue by micheljung** [FAForever/faf-moderator-client#15]
Allow to add/remove entries from/to the domain blacklist

**Comment by axel1200** [comment]
@micheljung Whats the daomain blacklist? Has it to do with Domains being blocked in IRC?

**Comment by Brutus5000** [comment]
There is a blacklist table in the db that is checked in user registration (faf-java-api).
This feature requires api support -> the domain blacklist must be exposed as an elide entity (create the entity class and set the right elide permissions).

**Comment by axel1200** [comment]
So Email domains right?

**Comment by Brutus5000** [comment]
Yes.

**Comment by Brutus5000** [comment]
API side implemented here https://github.com/FAForever/faf-java-api/pull/185
