### ISSUE TITLE
Notes per user

### ISSUE THREAD

**Issue by Viba** [FAForever/faf-moderator-client#16]
Would be useful in several scenarios if mods could save notes tied to a user. A simple text field that any mod can edit and view when searching for users would be really helpful.

In the UI maybe add a "Note" tab there, on the search result area e.g. display with an asterisk next to the ID to indicate there is a note for the user? Or alternatively show a note column in the search area that truncates long notes and leave the full viewing/editing capabilities for the tab.

**Comment by Brutus5000** [comment]
I suggest the following additional features:

One user can have many notes.
The author of the note is saved, as well as timestamp.
A note can be marked as "watched". There is a second panel where you can filter especially these notes. (Watch notes to inform other moderators about suspects of cheating/smurfing/whatever or to remind yourself or others about actions to perform).
