### ISSUE TITLE
Add search in Recent activity tab

### ISSUE THREAD

**Issue by Exotic-Retard** [FAForever/faf-moderator-client#2]
~~the newly registered users would be more useful if they contained a timestamp of registration.~~

~~a refresh list button or a function doing this every so often or some way of refreshing it would be great too. i believe this is already known about and just wasnt done in time, so no problem there.~~

being able to filter/search both the users and teamkills would be cool too!

**Comment by Brutus5000** [comment]
Please describe what is meant with "being able to filter/search both the users and tamkills" and how it is supposed to work.

**Comment by Exotic-Retard** [comment]
ok so for example in avatar management you are given a list of avatars and then a side search interface which filters that list down.

the current recent activity contains a very similar list, but no search interface. the improvement is to add this search as well so we can filter newly registered user list by name or email for example.

i dont know how hard this would be to make, but its functionality would be the same as in the avatars tab, so if its not hard it would be nice. if its hard, its not super important.

**Comment by Brutus5000** [comment]
Refresh button is handled here #8

**Comment by Brutus5000** [comment]
Timestamp of registration and other stuff is handled here #9

**Comment by axel1200** [comment]
@Exotic-Retard Ok let me try to understand. You wanna search a usere in the newly registered users, understood. But you could just search him in all users. That does not make a difference (does it). Ok it would if u searched for "*axel*" but then you could just sort the list by registration date and you will get the wanted result. 

Ok I can understand you wanna search Teamkills, but you could just search for the user how did that teamkill and sort the list by report date. Hmm what would be helpfull, would be one tab with "executed teamkill" and "suffered teamkills", so you could also find a teamkill if you only knew the victim. 

I mean of curse that would be more intuative to be able to also search the newly registered plays, but would not give you any benefit would it? What kind of querries did you think of?

**Comment by Brutus5000** [comment]
Nobody ever asked for it again. Closed due to lack of interest.
