### ISSUE TITLE
HASH, account link, and other identifying information returns a null when copied from the "reported accounts" tab.

### ISSUE THREAD

**Issue by IndexLibrorumProhibitorum** [FAForever/faf-moderator-client#207]
Using Magge's modified Mordor, I cannot say if this issue is present in the official version.

It's not possible to copy the relevant information directly from this tab, only when the player is looked up manually through the 'User management' tab.
![image](https://github.com/FAForever/faf-moderator-client/assets/64420140/c025a970-fa76-4bab-8d33-e2078cdf6dbb)

**Comment by Brutus5000** [comment]
What stops you from testing on the official one?

**Comment by IndexLibrorumProhibitorum** [comment]
Don't have it downloaded at the moment; I've been exclusively using the modified Mordor because it's significantly better.

**Comment by magge-faf** [comment]
Happens in official Mordor as well:

![image](https://github.com/FAForever/faf-moderator-client/assets/101107758/d2cb331c-3acf-460c-802d-caeb5f9226d6)

**Comment by magge-faf** [comment]
Update: I talked with index about the issue some long time ago; We can not think of any workflow that would require the user information in the report-tab. We always go to user-tab when we process users. The "null"-columns can be removed in report-tab, or fixed. Whatever is faster/better. Important is just the user-name and user-ID.
