### ISSUE TITLE
Caching of avatar images

### ISSUE THREAD

**Issue by Brutus5000** [FAForever/faf-moderator-client#34]
Right now, scrolling through an avatar list invokes a reload of all visible avatar images. This is invoncenient especially on small bandwithed connections.

**Comment by basalt79** [comment]
hi, i have currently a look on this item.
can anyone give me a raff estimate of the amount of items in the avatar images?
a possible solution can be a cache  used at UrlImageViewTableCell with key=url of the avatar.

whats your oppinion on this?

**Comment by Brutus5000** [comment]
Hi @basalt79 ,
we have ~250 avatar images. All images so are 40x20 pixel PNG with ~3kb.

In theory it is possible that the image behind the url changes even though it's probably pretty rar. In this case the updateTime of the AvatarFX instances changes.

I am totally unfamiliar with JavaFX caching, so I'm open for all solutions.

**Comment by basalt79** [comment]
hi @Brutus5000 , thx for the information. i will have a look on this.

**Comment by Brutus5000** [comment]
fixed by 0eb0550d0799f7bedf59179bf24988398a706fd8
