### ISSUE TITLE
See all current bans in a sortable list

### ISSUE THREAD

**Issue by Viba** [FAForever/faf-moderator-client#38]
Simply a list of current bans similar to user management, sortable by ban length/expiry date and such.

**Comment by Brutus5000** [comment]
@Viba You mean only those that are not yet expired, right?

**Comment by Viba** [comment]
@Brutus5000 I meant all bans, expired, permanent or temporary. It would help moderation work further.

**Comment by axel1200** [comment]
![image](https://user-images.githubusercontent.com/19996713/40120448-80e3d7ca-591f-11e8-847d-fc1d1b49d8e3.png)
Interesting one can ban himself
