### ISSUE TITLE
Enable moderators to force-rename a player

### ISSUE THREAD

**Issue by Brutus5000** [FAForever/faf-moderator-client#57]

**Comment by axel1200** [comment]
Is that possible with current api version?

**Comment by axel1200** [comment]
We should also be carefully, as the player can not login anymore then. Would we send out an email in this case? Or we need to have moderators tell them

**Comment by Brutus5000** [comment]
Not possible with current api, but it is a one-liner.
Yes moderators are aware not to use this without having contacted the player.
