### ISSUE TITLE
Add column technical name to tutorials table

### ISSUE THREAD

**Issue by axel1200** [FAForever/faf-moderator-client#65]
It is all there. I simply forgot to put it into the table. Needs to be added to ViewHelper.class in the method that generated the tutorial table.

**Comment by basalt79** [comment]
hi, i will have a look on this.

**Comment by axel1200** [comment]
Hi You might wanna consider joining your slack ;) We are really happy to help you.

**Comment by basalt79** [comment]
@RiotPharaoh i just did the pull request

**Comment by RiotPharaoh** [comment]
@basalt79 deleted my comment hoping that you won't see :D

**Comment by axel1200** [comment]
???

**Comment by Brutus5000** [comment]
Fixed by  3550268
