### ISSUE TITLE
Make search non-caps sensitive

### ISSUE THREAD

**Issue by Exotic-Retard** [FAForever/faf-moderator-client#80]
pretty much what it says on the tin.
previously, the search was non caps sensitive when you included asterisks in the search. it appears that this functionality is gone, and it would be nice to have it back

thanks :>

**Comment by Brutus5000** [comment]
The fact that is used to work for a short time was a side effect. We had to remove this as it brought a huge performance impact on the whole API.
This would be working again  if https://github.com/FAForever/db/issues/177 is ever solved.

**Comment by Brutus5000** [comment]
FAForever/db#177 has been resolved. Search should be case insensitive now.
