### ISSUE TITLE
fix hidden mod filter

### ISSUE THREAD

**Issue by PhilipJFryFAF** [FAForever/faf-moderator-client#98]
when searching in the mod vault and ticking the box to filter out hidden mod versions i still get all mods and the ones that are marked as hidden are not shown as such (see screenshot)
![image](https://user-images.githubusercontent.com/24656673/61908801-d64a5f00-af30-11e9-8e0d-e09a26212c94.png)
![image](https://user-images.githubusercontent.com/24656673/61908813-d9dde600-af30-11e9-8d6d-852046f425f6.png)
would be nice if that filter would hide the mods in question and not display them while showing them as not hidden

**Comment by Brutus5000** [comment]
I cannot reproduce the error. Are you aware that you have to click the search button again to actually apply your search criteria?

**Comment by PhilipJFryFAF** [comment]
yes - i hit the search button and then clicked on the mod to make sure

**Comment by PhilipJFryFAF** [comment]
uninstalled old java versions - can't reproduce my issue anymore
closing for now i guess
